name: Run X Feed Analysis

on:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'
  workflow_dispatch:  # Keep manual trigger option

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper git operations
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "X_BEARER_TOKEN=${{ secrets.X_BEARER_TOKEN }}" >> .env
        echo "X_ACCESS_TOKEN=${{ secrets.X_ACCESS_TOKEN }}" >> .env
        echo "X_ACCESS_TOKEN_SECRET=${{ secrets.X_ACCESS_TOKEN_SECRET }}" >> .env
        echo "X_API_KEY=${{ secrets.X_API_KEY }}" >> .env
        echo "X_API_KEY_SECRET=${{ secrets.X_API_KEY_SECRET }}" >> .env
        echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
        echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
      
    - name: Run analysis
      run: python run_analysis.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload analysis reports
      if: always()  # Run even if analysis fails
      uses: actions/upload-artifact@v3
      with:
        name: analysis-reports
        path: |
          analysis_report_*.txt
          error_posts_*.json
        retention-days: 7 